### DISCUSSION TITLE
Dynamic configuration with React?

### DISCUSSION THREAD

**Discussion by chasegarner** [uploadcare/file-uploader#338] [Q&A] [answered]
Dynamic configuration isn't working with React styles. I've got `--cfg-secure-signature` and `--cfg-secure-expire` set via the `style` attribute, and uploads fail with the "signature is required" error.

The web inspector shows that the style properties are correctly applied to `lr-file-uploader-inline`.

Moving the values into the css file fixes the problem, but that doesn't fit my use case.

Is there something I'm misunderstanding?

```typescript
// SimpleUploader.tsx

import React from "react";

import * as LR from "@uploadcare/blocks";
import "@uploadcare/blocks/web/lr-basic.min.css";

import st from "./SimpleUploader.module.css";

LR.registerBlocks(LR);

interface Props {
  signature: string;
  expire: number;
}

export function SimpleUploader(props: Props) {
  const classNames = ["lr-wgt-common", st.uploaderCfg].join(" ");

  return (
    <lr-file-uploader-inline
      class={classNames}
      style={{
        "--cfg-secure-signature": props.signature,
        "--cfg-secure-expire": `${props.expire}`,
      }}
    />
  );
}

```

```css
/* SimpleUploader.module.css */

.uploaderCfg {
  --ctx-name: 'uploader';
  --cfg-pubkey: "<key>";
  --cfg-multiple: 1;
  --cfg-confirm-upload: 1;
  --cfg-img-only: 0;
  --cfg-accept: "";
  --cfg-store: 1;
  --cfg-camera-mirror: 0;
  --cfg-source-list: "local, url, camera, dropbox, gdrive";
  --cfg-max-files: 10;
}

```
