### DISCUSSION TITLE
HTMLElement is not defined

### DISCUSSION THREAD

**Discussion by heymartinadams** [uploadcare/file-uploader#405] [blocks] [answered]
For some reason, getting this error. Installed via npm `@uploadcare/blocks@0.19.0`.

How do I get the props `expire` and `signature`? Documentation is incredibly sparse.

<img width="994" alt="CleanShot 2023-03-21 at 14 13 15@2x" src="https://user-images.githubusercontent.com/11673745/226742235-d48d348a-0087-489f-bacc-f3c6de90f8a3.png">

## React using NextJS
```js
// Packages
import * as LR from '@uploadcare/blocks'
import { PACKAGE_VERSION } from '@uploadcare/blocks/env'
// Layouts
import Logo from '^/logo'
import config from './upload.module.css'

LR.registerBlocks(LR)

const DesignLayoutsHome = ({ expire, signature }) => {
  return (
    <section className='p-8 max-w-4xl mx-auto flex flex-col items-center justify-center'>
      <Logo />

      <div className='flex flex-col gap-8 p-8'>
        <lr-file-uploader-inline
          className={config?.uploaderCfg}
          css-src={`https://unpkg.com/@uploadcare/blocks@${PACKAGE_VERSION}/web/file-uploader-regular.min.css`}
          style={{
            '--cfg-secure-signature': `"${signature}"`,
            '--cfg-secure-expire': `${expire}`
          }}
        />
      </div>
    </section>
  )
}

export default DesignLayoutsHome

```

## upload.module.css
```css
.uploaderCfg {
  --ctx-name: 'uploader';
  --cfg-pubkey: '<key>'; /* removed for this public post */
  --cfg-multiple: 1;
  --cfg-confirm-upload: 1;
  --cfg-img-only: 0;
  --cfg-accept: '';
  --cfg-store: 1;
  --cfg-camera-mirror: 0;
  --cfg-source-list: 'local, url, camera, dropbox, gdrive';
  --cfg-max-files: 10;
}
```
